### PR TITLE
use utcfromtimestamp instead of timezone.utc

### PR DESCRIPTION
**Pull request by niketanpatel**
as requested in #44

### CODE REVIEW

**Comment by niketanpatel** [comment]
tested:

```
[2019-02-06 17:15:58] $ docker-compose run ingest \
>     --output "/home/jovyan/work/mds/data/" \
>     --providers Bird \
>     --status_changes \
>     --start_time 1 \
>     --end_time 2 \
>     --stage_first 3
Run time: 2019-02-07T01:16:14.877593
Reading config file: /home/jovyan/work/mds/.config
Referencing MDS @ master
Downloading provider registry...
Acquired registry: JUMP, Lime, Bird, Razor, Lyft, Skip, HOPR, Wheels, Spin, WIND
Requesting status_changes from Bird
Time range: 1970-01-01T00:00:01 to 1970-01-01T00:00:02
Got payload with 0 status_changes
Validating status_changes
Validating data from Bird
Validated 0 records (0 passed)
Writing data files to /home/jovyan/work/mds/data/
status_changes complete
```

**Comment by thekaveman** [comment]
This is fine, but what I meant was to change all of this together in one PR.

**Comment by niketanpatel** [comment]
the 2 PRs are different -- #44 is fixing a runtime error, and this one is just a QoL improvement, so i've decided to keep them separate, since the commit messages reflect exactly what these changes are doing

with this in mind, do you still want them merged into 1 PR?

**Comment by thekaveman** [comment]
Fair enough.

**Pull request merged**
